Resources:
  usersTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: notes
    SSESpecification:
      SSEEnabled: true
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: userId
        AttributeType: S
      - AttributeName: noteId
        AttributeType: S
    KeySchema:
      - AttributeName: userId
        KeyType: HASH
      - AttributeName: noteId
        KeyType: RANGE
